//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class libro
    {
        public int codigo { get; set; }
        public string nombre { get; set; }
        public string empresa { get; set; }
        public int precio { get; set; }
        public int stock { get; set; }
        public int reservas { get; set; }
    }
}
